[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

; Partition scheme pour permettre l'utilisation de la reconnaissance faciale
board_build.partitions = huge_app.csv

; Bibliothèques requises
lib_deps =
    espressif/esp32-camera@^2.0.4

; Options de build
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Configuration du moniteur série
monitor_filters =
    esp32_exception_decoder
    time
